name: Case Study Submission
description: Submit a reproducible solution
title: "[CASE] "
body:
  - type: textarea
    id: summary
    attributes:
      label: Executive summary
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy
      options:
        - label: I used synthetic/de-identified data only.
          required: true
