from pathlib import Path
from datetime import datetime,timedelta
import csv,json,random
from openpyxl import Workbook
from openpyxl.styles import Font,PatternFill,Alignment
R=Path(__file__).resolve().parents[1]; random.seed(42)
for d in ['data/raw_synthetic','data/processed','data/data_dictionary','excel','notebooks','src','assignments/beginner','assignments/intermediate','assignments/advanced','case_study','docs','release','.github/ISSUE_TEMPLATE','.github/DISCUSSION_TEMPLATE']: (R/d).mkdir(parents=True,exist_ok=True)
def csvw(p,rows):
 with (R/p).open('w',newline='',encoding='utf-8-sig') as f:w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
def txt(p,s): (R/p).write_text(s,encoding='utf-8')
locs={'Reception':(1,'Main','Registration'),'Medicine OPD':(3,'Main','Consultation'),'Cardiology':(5,'Main','Consultation'),'Lab A':(2,'Diagnostic','Laboratory'),'Lab B':(4,'Diagnostic','Laboratory'),'Radiology A':(3,'Diagnostic','Imaging'),'Radiology B':(6,'Diagnostic','Imaging'),'ECG':(5,'Main','Cardiac Test'),'Ultrasound':(7,'Diagnostic','Imaging'),'Central Billing':(1,'Main','Billing'),'Report Hub':(1,'Main','Reports'),'Exit':(1,'Main','Exit')}
nodes=[{'node_id':f'N{i:02d}','node_name':n,'building':b,'floor':f,'service_type':s} for i,(n,(f,b,s)) in enumerate(locs.items(),1)];nid={x['node_name']:x['node_id'] for x in nodes}
ep=[('Reception','Medicine OPD',180),('Reception','Cardiology',220),('Medicine OPD','Lab A',220),('Medicine OPD','Lab B',310),('Medicine OPD','Radiology A',260),('Medicine OPD','ECG',180),('Medicine OPD','Ultrasound',420),('Cardiology','Lab A',260),('Cardiology','Lab B',210),('Cardiology','Radiology A',240),('Cardiology','ECG',80),('Cardiology','Ultrasound',330),('Lab A','Radiology A',120),('Lab A','ECG',210),('Lab A','Ultrasound',280),('Lab B','Radiology B',110),('Lab B','ECG',130),('Lab B','Ultrasound',180),('Radiology A','ECG',150),('Radiology B','Ultrasound',90),('ECG','Ultrasound',170),('Lab A','Central Billing',260),('Lab B','Central Billing',330),('Radiology A','Central Billing',280),('Radiology B','Central Billing',390),('ECG','Central Billing',210),('Ultrasound','Central Billing',420),('Central Billing','Report Hub',60),('Report Hub','Exit',40)]
edges=[{'edge_id':f'E{i:03d}','from_node':nid[a],'to_node':nid[b],'distance_m':d,'expected_walk_min':round(d/75,2),'bidirectional':True} for i,(a,b,d) in enumerate(ep,1)]
svc={'CBC':('Laboratory',700),'HbA1c':('Laboratory',1200),'Blood Glucose':('Laboratory',450),'Lipid Profile':('Laboratory',1400),'Chest X-Ray':('Imaging',1200),'ECG':('Cardiac Test',900),'Ultrasound Abdomen':('Imaging',2200)}; sl={'Laboratory':['Lab A','Lab B'],'Imaging':['Radiology A','Radiology B'],'Cardiac Test':['ECG']}
patients=[{'patient_id':f'P{i:06d}','age_band':random.choice(['0-17','18-29','30-44','45-59','60+']),'sex':random.choice(['Female','Male']),'identity_method':random.choices(['QR','NFC','Mobile Token','Manual ID'],[.35,.30,.20,.15])[0],'synthetic':True} for i in range(1,1201)]
enc=[];orders=[];tasks=[];queues=[];bill=[];journey=[];on=tn=qn=bn=0; start=datetime(2026,7,1,7)
for e in range(1,1801):
 p=random.choice(patients);eid=f'ENC{e:06d}';arr=start+timedelta(minutes=random.randint(0,43200));dept=random.choices(['Medicine OPD','Cardiology'],[.72,.28])[0];n=random.choices([1,2,3,4,5],[.30,.28,.22,.14,.06])[0];ss=random.sample(list(svc),n);reg=random.randint(4,10);newreg=random.randint(1,3);base=reg+n*random.uniform(3,5.5)+random.uniform(6,15);new=newreg+random.uniform(4,11);bw=250+n*random.randint(180,420)+n*random.randint(90,180);nw=180+n*random.randint(100,240)+random.randint(40,100);enc.append({'encounter_id':eid,'patient_id':p['patient_id'],'arrival_ts':arr.isoformat(timespec='minutes'),'doctor_department':dept,'ordered_service_count':n,'status':'Completed'});total=0
 for s in ss:
  on+=1;tn+=1;qn+=1;bn+=1;oid=f'ORD{on:07d}';cat,price=svc[s];total+=price;orders.append({'order_id':oid,'encounter_id':eid,'patient_id':p['patient_id'],'service_name':s,'service_category':cat,'ordered_ts':(arr+timedelta(minutes=reg+random.randint(8,30))).isoformat(timespec='minutes'),'clinical_priority':random.choices(['Routine','Urgent'],[.9,.1])[0],'order_status':'Completed'});place='Ultrasound' if s=='Ultrasound Abdomen' else random.choice(sl[cat]);tasks.append({'task_id':f'TSK{tn:07d}','order_id':oid,'encounter_id':eid,'assigned_location':place,'task_status':'Completed','routing_method':random.choices(['Rules+Optimization','Manual Override'],[.92,.08])[0],'estimated_wait_min':random.randint(3,22),'actual_wait_min':random.randint(2,28)});queues.append({'queue_event_id':f'QE{qn:07d}','encounter_id':eid,'service_name':s,'location':place,'queue_wait_min':random.randint(2,28),'service_time_min':random.randint(4,18),'sla_breach':random.random()<.16});disc=random.choice([0,0,0,50,100]);bill.append({'ledger_id':f'BL{bn:07d}','encounter_id':eid,'patient_id':p['patient_id'],'service_name':s,'department':place,'gross_charge_bdt':price,'discount_bdt':disc,'patient_payable_bdt':price-disc,'billing_mode':'Central Ledger','payment_status':'Settled'})
 journey.append({'encounter_id':eid,'patient_id':p['patient_id'],'service_count':n,'baseline_payment_touchpoints':n,'centralized_payment_touchpoints':1,'baseline_admin_minutes':round(base,2),'redesigned_admin_minutes':round(new,2),'baseline_walking_m':bw,'redesigned_walking_m':nw,'total_payable_bdt':total})
staff=[]
for d in range(14):
 date=(datetime(2026,7,1)+timedelta(days=d)).date().isoformat()
 for l in ['Reception','Central Billing','Lab A','Lab B','Radiology A','Radiology B','ECG','Ultrasound']:
  for sh in ['Morning','Evening']:
   n=random.randint(3,7);staff.append({'date':date,'location':l,'shift':sh,'scheduled_staff':n,'active_staff':max(1,n-random.choice([0,0,1])),'training_band':random.choice(['Basic','Intermediate','Advanced'])})
for p,r in [('data/raw_synthetic/patients.csv',patients),('data/raw_synthetic/encounters.csv',enc),('data/raw_synthetic/service_orders.csv',orders),('data/raw_synthetic/workflow_tasks.csv',tasks),('data/raw_synthetic/queue_events.csv',queues),('data/raw_synthetic/billing_ledger.csv',bill),('data/raw_synthetic/hospital_nodes.csv',nodes),('data/raw_synthetic/hospital_edges.csv',edges),('data/raw_synthetic/staff_shifts.csv',staff),('data/processed/journey_summary.csv',journey)]:csvw(p,r)
dd=[]
for t,r in [('patients',patients),('encounters',enc),('service_orders',orders),('workflow_tasks',tasks),('queue_events',queues),('billing_ledger',bill),('hospital_nodes',nodes),('hospital_edges',edges),('staff_shifts',staff),('journey_summary',journey)]:
 for k,v in r[0].items():dd.append({'table':t,'field':k,'type':type(v).__name__,'description':k.replace('_',' ').capitalize(),'privacy_class':'Synthetic / non-identifying'})
csvw('data/data_dictionary/data_dictionary.csv',dd)
docs={'PROJECT_CHARTER.md':'# Project Charter — v0.1.0\n\nSynthetic HR Operations × healthcare operations case study. Clinician owns clinical decisions; workflow/routing/billing are operational; HRBP evaluates staffing, training, job design, productivity and ROI.\n','ROADMAP.md':'# Version Roadmap\n\n- ✅ v0.1.0 Foundation & baseline\n- v0.2.0 Identity resolution\n- v0.3.0 Front Desk Control Tower\n- v0.4.0 Queue/routing/navigation\n- v0.5.0 Central billing/reports\n- v0.6.0 HR Operations\n- v0.7.0 Financial model\n- v0.8.0 Predictive operations\n- v0.9.0 Community beta\n- v1.0.0 Portfolio release\n','DATA_PROVENANCE.md':'# Data Provenance\n\nAll records are synthetic. No real patient, biometric, billing or employee records are included.\n','SECURITY.md':'# Security & Privacy\n\nPublic data must remain synthetic/de-identified. Never commit credentials or real patient/biometric data. Operational AI does not replace clinical judgment.\n','DATASET_USAGE_GUIDE.md':'# Dataset Usage Guide\n\nStart with `data/processed/journey_summary.csv`, then raw tables, Excel, and notebooks.\n','CHANGELOG.md':'# Changelog\n\n## v0.1.0\nFoundation synthetic datasets, hospital graph, Excel starter, notebooks, assignments and submission templates.\n','LICENSE':'MIT License for code/docs. Synthetic dataset intended for CC BY 4.0 educational reuse.\n','requirements.txt':'openpyxl>=3.1,<4\n','docs/ARCHITECTURE.md':'# Architecture\n\nPatient → Doctor → Service Order → Workflow Task → Front Desk → Service Node → Central Billing → Report Hub → Exit.\n','case_study/problem_statement.md':'# Case Study\n\nRecommend staffing, process, technology or hybrid intervention using patient-time, workforce and financial evidence.\n','case_study/evaluation_rubric.md':'# Rubric — 100\n\nProblem 10; data 15; flow 15; HR 15; finance 15; routing 10; visualization 10; recommendation 10.\n','assignments/beginner/README.md':'# Beginner\nBuild an Excel baseline-vs-redesign dashboard.\n','assignments/intermediate/README.md':'# Intermediate\nAnalyze queue, service, staffing and billing touchpoints in Python.\n','assignments/advanced/README.md':'# Advanced\nBuild a rules-first queue-aware routing model and intervention comparison.\n','release/RELEASE_NOTES_v0.1.0.md':'# Release Notes v0.1.0\n\nFoundation release; synthetic data only.\n','release/V0.1.0_RELEASE_MANIFEST.md':'# v0.1.0 Manifest\n\nHero files: Excel workbook, journey summary, roadmap and charter.\n'}
for p,s in docs.items():txt(p,s)
txt('CITATION.cff','cff-version: 1.2.0\ntitle: "Bangladesh Hospital Digital Patient Journey & HR Operations Analytics"\nversion: 0.1.0\nauthors:\n  - family-names: "Musa"\n    given-names: "Musa"\nlicense: MIT\n');txt('MANIFEST.json',json.dumps({'version':'0.1.0','synthetic_only':True,'counts':{'patients':len(patients),'encounters':len(enc),'service_orders':len(orders),'workflow_tasks':len(tasks),'queue_events':len(queues),'billing_rows':len(bill),'staff_shift_rows':len(staff)}},indent=2));txt('dataset-metadata.json',json.dumps({'title':'Bangladesh Hospital Digital Patient Journey Analytics - Synthetic','id':'samusa099/bd-patient-journey-analytics','licenses':[{'name':'CC-BY-4.0'}]},indent=2));txt('src/routing.py','from collections import defaultdict\nimport heapq\ndef build_graph(edges):\n g=defaultdict(list)\n for e in edges:g[e["from_node"]].append((e["to_node"],float(e["expected_walk_min"])))\n return g\n')
txt('.github/ISSUE_TEMPLATE/case-study-submission.yml','name: Case Study Submission\ndescription: Submit a completed analysis\ntitle: "[CASE] "\nbody:\n  - type: textarea\n    id: summary\n    attributes:\n      label: Executive summary\n    validations:\n      required: true\n');txt('.github/DISCUSSION_TEMPLATE/solution-idea.yml','title: "[IDEA] "\nbody:\n  - type: textarea\n    id: solution\n    attributes:\n      label: Proposed solution\n')
for fn,title,path in [('01_inspect_synthetic_data.ipynb','Inspect Synthetic Data','../data/raw_synthetic/encounters.csv'),('02_patient_flow_analysis.ipynb','Patient Flow Analysis','../data/processed/journey_summary.csv'),('03_central_billing_analysis.ipynb','Central Billing Analysis','../data/raw_synthetic/billing_ledger.csv')]:
 nb={'cells':[{'cell_type':'markdown','metadata':{},'source':[f'# {title}\n']},{'cell_type':'code','execution_count':None,'metadata':{},'outputs':[],'source':[f"import csv\nfrom pathlib import Path\nwith open(Path('{path}'),encoding='utf-8-sig') as f: rows=list(csv.DictReader(f))\nprint(len(rows))"]}],'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'}},'nbformat':4,'nbformat_minor':5};txt('notebooks/'+fn,json.dumps(nb,indent=2))
wb=Workbook();d=wb.active;d.title='Executive Dashboard';j=wb.create_sheet('Journey Summary');b=wb.create_sheet('Billing Ledger');s=wb.create_sheet('Scenario Model');x=wb.create_sheet('Data Dictionary');blue='1F4E78';white='FFFFFF';dark='17365D';d.merge_cells('A1:H2');d['A1']='Digital Patient Journey — v0.1.0';d['A1'].font=Font(bold=True,color=white,size=16);d['A1'].fill=PatternFill('solid',fgColor=dark);d['A1'].alignment=Alignment(horizontal='center');d['A4']='KPI';d['B4']='Value';metrics=[('Avg baseline admin min',sum(r['baseline_admin_minutes'] for r in journey[:600])/600),('Avg redesigned admin min',sum(r['redesigned_admin_minutes'] for r in journey[:600])/600),('Avg minutes saved',sum(r['baseline_admin_minutes']-r['redesigned_admin_minutes'] for r in journey[:600])/600),('Avg baseline payment touches',sum(r['baseline_payment_touchpoints'] for r in journey[:600])/600),('Avg centralized payment touches',1)];
for i,(k,v) in enumerate(metrics,5):d.cell(i,1,k);d.cell(i,2,round(v,2))
for ws,rows in [(j,journey[:600]),(b,bill[:800]),(x,dd)]:
 ws.append(list(rows[0]));[ws.append([r[k] for k in rows[0]]) for r in rows];ws.freeze_panes='A2';[(setattr(c,'fill',PatternFill('solid',fgColor=blue)),setattr(c,'font',Font(bold=True,color=white))) for c in ws[1]]
s.append(['Input','Value']);[s.append(z) for z in [('Annual encounters',180000),('Baseline admin min',36),('Redesigned admin min',14),('Loaded staff cost/hour',250),('Implementation cost',4500000)]]
for ws in wb.worksheets:
 for i in range(1,min(ws.max_column,12)+1):ws.column_dimensions[chr(64+i)].width=20
wb.save(R/'excel/Hospital_Patient_Journey_Analytics_v0.1.xlsx')
txt('scripts/validate_project.py','from pathlib import Path\nimport json,zipfile,sys\nR=Path(__file__).resolve().parents[1]\nreq=["README.md","ROADMAP.md","MANIFEST.json","data/processed/journey_summary.csv","excel/Hospital_Patient_Journey_Analytics_v0.1.xlsx"]\ne=[p for p in req if not (R/p).exists()]\nfor p in R.rglob("*.xlsx"):\n e += [] if zipfile.is_zipfile(p) else [str(p)]\nprint("PASS: v0.1.0 validated" if not e else "FAIL: "+str(e));sys.exit(bool(e))\n')
print('Built v0.1.0',len(patients),len(enc),len(orders))
